In [1]:
from google.colab import drive
drive.mount("/content/drive")

MessageError: Error: credential propagation was unsuccessful

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"swapnapalchowdhury","key":"0f1845ad81e40863feddd63e775cf3fd"}'}

In [ ]:
!mkdir-p~/.kaggle
!cp kaggle.json~/.kaggle
!chmod 600~/.kaggle.json

/bin/bash: line 1: mkdir-p~/.kaggle: No such file or directory
cp: missing destination file operand after 'kaggle.json~/.kaggle'
Try 'cp --help' for more information.
chmod: missing operand after ‘600~/.kaggle.json’
Try 'chmod --help' for more information.

In [ ]:
!kaggle datasets download -d sumanbera19/bengaluru-house-price-dataset

Dataset URL: https://www.kaggle.com/datasets/sumanbera19/bengaluru-house-price-dataset
License(s): CC0-1.0
Downloading bengaluru-house-price-dataset.zip to /content
100% 194k/194k [00:00<00:00, 375kB/s]

In [ ]:
import zipfile

In [ ]:
with zipfile.ZipFile("bengaluru-house-price-dataset.zip") as z:
  z.extractall("HOUSE")

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data= pd.read_csv("/content/HOUSE/bengaluru_house_prices.csv")
df=pd.DataFrame(data)
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [ ]:
df.shape

(13320, 9)

In [ ]:
df.info

<bound method DataFrame.info of                   area_type   availability                  location  \
0      Super built-up  Area         19-Dec  Electronic City Phase II
1                Plot  Area  Ready To Move          Chikka Tirupathi
2            Built-up  Area  Ready To Move               Uttarahalli
3      Super built-up  Area  Ready To Move        Lingadheeranahalli
4      Super built-up  Area  Ready To Move                  Kothanur
...                     ...            ...                       ...
13315        Built-up  Area  Ready To Move                Whitefield
13316  Super built-up  Area  Ready To Move             Richards Town
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar
13318  Super built-up  Area         18-Jun           Padmanabhanagar
13319  Super built-up  Area  Ready To Move              Doddathoguru

            size  society total_sqft  bath  balcony   price
0          2 BHK  Coomee        1056   2.0      1.0   39.07
1      4 Bedroom  Theanmp       2600   5.0      3.0  120.00
2          3 BHK      NaN       1440   2.0      3.0   62.00
3          3 BHK  Soiewre       1521   3.0      1.0   95.00
4          2 BHK      NaN       1200   2.0      1.0   51.00
...          ...      ...        ...   ...      ...     ...
13315  5 Bedroom  ArsiaEx       3453   4.0      0.0  231.00
13316      4 BHK      NaN       3600   5.0      NaN  400.00
13317      2 BHK  Mahla T       1141   2.0      1.0   60.00
13318      4 BHK  SollyCl       4689   4.0      1.0  488.00
13319      1 BHK      NaN        550   1.0      1.0   17.00

[13320 rows x 9 columns]>

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [ ]:
df.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [ ]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(6201)

In [ ]:
df.size

119880

In [ ]:
df1=df.dropna()
df1.shape

(7496, 9)

In [ ]:
a=df.isnull().sum()/df.shape[0]*100
a

area_type        0.000000
availability     0.000000
location         0.007508
size             0.120120
society         41.306306
total_sqft       0.000000
bath             0.548048
balcony          4.572072
price            0.000000
dtype: float64

In [ ]:
b=a[a>17].keys()
b

Index(['society'], dtype='object')

In [ ]:
df.drop(b,axis=1,inplace=True)
df

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,1.0,1.0,17.00

In [ ]:
cat_col=df.select_dtypes(include=["object"]).columns.tolist()
cat_col

['area_type', 'availability', 'location', 'size', 'total_sqft']

In [ ]:
num_col=df.select_dtypes(include=["int64","float64"]).columns.tolist()
num_col

['bath', 'balcony', 'price']

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
cat_clean=SimpleImputer(strategy="most_frequent")
num_clean=SimpleImputer(strategy="mean")

In [ ]:
df[cat_col]=cat_clean.fit_transform(df[cat_col])
df[num_col]=num_clean.fit_transform(df[num_col])

In [ ]:
df.isnull().sum()

area_type       0
availability    0
location        0
size            0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

In [ ]:
df

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.000000,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.000000,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.000000,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.000000,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.000000,51.00
...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.000000,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,3600,5.0,1.584376,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.000000,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689,4.0,1.000000,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,1.0,1.000000,17.00

In [ ]:
df["price"]=df["price"]*10000
df

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.000000,3.907000e+11
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.000000,1.200000e+12
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.000000,6.200000e+11
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.000000,9.500000e+11
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.000000,5.100000e+11
...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.000000,2.310000e+12
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,3600,5.0,1.584376,4.000000e+12
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.000000,6.000000e+11
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689,4.0,1.000000,4.880000e+12
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,1.0,1.000000,1.700000e+11

In [ ]:
x = df['size'].apply(lambda x: int(x.split(' ')[0]))
x

0        2
1        4
2        3
3        3
4        2
        ..
13315    5
13316    4
13317    2
13318    4
13319    1
Name: size, Length: 13320, dtype: int64

In [ ]:
df.insert(4,"BHK",x)
df

,area_type,availability,location,size,BHK,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,2,1056,2.0,1.000000,3.907000e+11
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,4,2600,5.0,3.000000,1.200000e+12
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,3,1440,2.0,3.000000,6.200000e+11
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,3,1521,3.0,1.000000,9.500000e+11
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,2,1200,2.0,1.000000,5.100000e+11
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,5,3453,4.0,0.000000,2.310000e+12
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,4,3600,5.0,1.584376,4.000000e+12
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,2,1141,2.0,1.000000,6.000000e+11
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4,4689,4.0,1.000000,4.880000e+12
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,1,550,1.0,1.000000,1.700000e+11

In [ ]:
def convert_sqft_to_num(x):
    if isinstance(x, float):
        return x
    if not isinstance(x, str):
        return None
    tokens = x.split('-')
    if len(tokens) == 2:
        return (float(tokens[0]) + float(tokens[1]))/2
    try:
        return float(x)
    except:
        return None

df['total_sqft'] = df['total_sqft'].apply(convert_sqft_to_num)
df['price_per_sqft'] = df['price'] / df['total_sqft']
display(df.head())

,area_type,availability,location,size,BHK,total_sqft,bath,balcony,price,price_per_sqft
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,2,1056.0,2.0,1.0,3.907000e+11,3.699811e+08
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,4,2600.0,5.0,3.0,1.200000e+12,4.615385e+08
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,3,1440.0,2.0,3.0,6.200000e+11,4.305556e+08
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,3,1521.0,3.0,1.0,9.500000e+11,6.245891e+08
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,2,1200.0,2.0,1.0,5.100000e+11,4.250000e+08

In [ ]:
def check(x):
  try:
    float(x)
    return True
  except:
    return False

In [3]:
# Ensure df is defined. If you get a NameError, please re-run the cell where you loaded the CSV.
try:
    # Since total_sqft was converted to numeric in cell 25df4adb,
    # we check for any remaining nulls or non-numeric values.
    z = df[df['total_sqft'].isna()]
    display(z)
except NameError:
    print("Error: 'df' is not defined. Please run the data loading and preprocessing cells above first.")

Error: 'df' is not defined. Please run the data loading and preprocessing cells above first.

In [4]:
import pandas as pd
import numpy as np

# Re-loading the data to define 'df' again
try:
    data = pd.read_csv("/content/HOUSE/bengaluru_house_prices.csv")
    df = pd.DataFrame(data)
    print("Successfully re-defined 'df'. You can now run the preprocessing and analysis cells again.")
except FileNotFoundError:
    print("Dataset file not found. Please ensure the extraction cell (55tOvHPWWMJ7) was run successfully.")

Dataset file not found. Please ensure the extraction cell (55tOvHPWWMJ7) was run successfully.